#!/usr/bin/zsh
# See the 'Character Highlighting' section of zshzle(1).

# declare the array to tweak
typeset -A ZSH_HIGHLIGHT_STYLES

# For a comprehensive list of highlighters, please refer to:
# (https://github.com/zsh-users/zsh-syntax-highlighting/tree/master/highlighters/main)

# MAIN HIGHLIGHTERS
ZSH_HIGHLIGHT_STYLES[arg0]='fg=63,bold' # fallback command style
#ZSH_HIGHLIGHT_STYLES[alias]='fg=69,bold'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=30,bold' # shell builtin commands (shift, pwd)
ZSH_HIGHLIGHT_STYLES[command]='fg=69,bold' # commands (zsh, nvim)
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#94e2d5' # command options (--help, --verbose)
#ZSH_HIGHLIGHT_STYLES[function]='fg=69,bold' # function names
ZSH_HIGHLIGHT_STYLES[precommand]='fg=30' # precommand modifiers (noglob, builtin)
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=75' # command separation tokens (; && ||)
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=62' # unknown syntax, commands, tokens
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=70' # shell reserved words (if, for, while)
ZSH_HIGHLIGHT_STYLES[autodirectory]='fg=42,underline'
ZSH_HIGHLIGHT_STYLES[path]='fg=42' # incomplete file paths
ZSH_HIGHLIGHT_STYLES[globbing]='fg=27,bold' # glob patterns (*, $, ^)
ZSH_HIGHLIGHT_STYLES[comment]='fg=243' # setopt INTERACTIVE_COMMENTS must be set
#ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=32,bold'
#ZSH_HIGHLIGHT_STYLES[command-substitution]='none'
#ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg=magenta'
#ZSH_HIGHLIGHT_STYLES[process-substitution]='none'
#ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg=magenta'
#ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='none'
#ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='none'
#ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='none'
#ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]='fg=magenta'
#ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=yellow'
#ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=yellow'
#ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=yellow'
#ZSH_HIGHLIGHT_STYLES[rc-quote]='fg=cyan'
#ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=cyan'
#ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=cyan'
#ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=cyan'
#ZSH_HIGHLIGHT_STYLES[assign]='none' # parameter assignments (x=foo and x=( ))
#ZSH_HIGHLIGHT_STYLES[redirection]='fg=yellow' # redirection operators (<, >, etc)
#ZSH_HIGHLIGHT_STYLES[named-fd]='none' # named file descriptor (the fd in echo foo {fd}>&2)
#ZSH_HIGHLIGHT_STYLES[numeric-fd]='none' # numeric file descriptor (the 2 in echo foo {fd}>&2)
#ZSH_HIGHLIGHT_STYLES[default]='none' # everything else

# BRACKETS
#ZSH_HIGHLIGHT_STYLES[bracket-error]='fg=red,bold'
#ZSH_HIGHLIGHT_STYLES[bracket-level-1]='fg=blue,bold'
#ZSH_HIGHLIGHT_STYLES[bracket-level-2]='fg=green,bold'
#ZSH_HIGHLIGHT_STYLES[bracket-level-3]='fg=magenta,bold'
#ZSH_HIGHLIGHT_STYLES[bracket-level-4]='fg=yellow,bold'
#ZSH_HIGHLIGHT_STYLES[bracket-level-5]='fg=cyan,bold'
#ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]='standout'

# CURSOR
#ZSH_HIGHLIGHT_STYLES[cursor]='standout'

# LINE
#ZSH_HIGHLIGHT_STYLES[line]='bold'
